spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create
  datasource:
    password: myp5011
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myp
    url: jdbc:mysql://localhost:3306/itwill?serverTimezone=Asia/Seoul
  sql:
    init:
      mode: never
logging:
  level:
    org:
      springframework:
        web: debug
        context: debug
        beans: debug
      hibernate:
        orm:
          jdbc:
            bind: trace
        nodeValue: info
        SQL: debug
        type:
          descriptor:
            sql: trace
server:
  port: '8080'
